### ISSUE TITLE
Add-in activation rule

### ISSUE THREAD

**Issue by vtiti** [OfficeDev/office-js-docs-reference#192]
The [Clients](https://docs.microsoft.com/en-us/javascript/office/requirement-sets/outlook-api-requirement-sets?view=office-js#clients) section describes the requirement set for the platform.

I have an Exchange 2016 On-Premises installation, and I set the **Requirements** element to **1.5**.
Regarding the documentation my addin should not be activated in the Exchange 2016 OWA.
If I use the [runtime check of the supported version](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/specify-office-hosts-and-api-requirements#use-runtime-checks-in-your-javascript-code), it says the **1.5** version supported.

Then I tried to use the REST API from my add-in like [decribed here](https://docs.microsoft.com/en-us/outlook/add-ins/use-rest-api) but it didn't worked (I got 405 Method Not Allowed).

But I cannot able to use the Exchange Server REST API because it is only supported with hybrid Exchange installation.

Why the add-in activated if I cannot use it properly? 
Or at least the documentation should be extended to explain this exception. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46d8b63e-2e0c-99bd-e089-eacb33a90645
* Version Independent ID: 87e3cf4d-285b-67e8-8a3f-ff623a4bd9fa
* Content: [Outlook JavaScript API requirement sets](https://docs.microsoft.com/en-us/javascript/office/requirement-sets/outlook-api-requirement-sets?view=office-js)
* Content Source: [docs/docs-ref-conceptual/requirement-sets/outlook-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-conceptual/requirement-sets/outlook-api-requirement-sets.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc: Please take a look at this scenario.
@vtiti: Are you able to tell which method was not allowed?

**Comment by vtiti** [comment]
I would like to clarify a little:
I made an Outlook addin, which using the O365 REST API to get the current email attachments.

I published the addin in the AppSource.

One of our customer wants to use the addin on their Exchange 2016 On-Premises installation. 

I was able to load the addin when I tried it on my test Exchange 2016 installation.
My problem was: as I stated in the manifest I supporting the 1.5 version javascript API, it shouldn't be loaded into the Exchange 2016 OWA, as it only supports the 1.3 javascript API. But it loaded, and it is suboptimal: 
- I'm using the pin feature in my addin (it works with O365, but not on the Exchange). 
- the REST API is not supported by the documentation, and I got 405 error for my REST API request (it works with O365, but not on the Exchange). 
- I tried to workaround the REST API issue, by using the runtime check method for the [getCallbackTokenAsync](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.5/office.context.mailbox#getcallbacktokenasyncoptions-callback) call, and it says it is supported both on O365 and Exchange.

I was able to use the REST API on the Exchange 2016 in the end of the day, enabling the CORS on the Exchange 2016 server's IIS. 

My question really was: is the documentation wrong, or the Exchange server? What is the supported way to determine if I using my addin hosted on O365 or On-Premises?

**Comment by exextoc** [comment]
This seems like a bug in Exchange 2016 OWA. If a client reports that it supports a certain requirement set (e.g. 1.3), it shouldn't receive add-ins that are installed on the mailbox that have a minimum requirement set about that (like 1.5)

**Comment by schmkr** [comment]
Hi @exextoc, I would like to add here, this same bug also is still present in Exchange 2019.

As reported by our colleague @sarea in OfficeDev/office-js#991, some customers of us are facing CORS issues when they try to run our (self-hosted) OWA Add-in on their Exchange 2019 server, when our Add-In is trying to request the rest API that is defined at `Office.context.mailbox.restUrl`.

We have tried, but up to now, without any luck, to configure IIS to allow CORS requests. We also posted [this question on SO](https://stackoverflow.com/questions/60376939/exchange-on-premise-owa-rest-api-not-handling-cors-preflight-correctly), since we cannot find any relevant documentation on the subject anywhere.

Is there any documentation available somewhere that explains how to configure IIS to allow self hosted OWA Add-ins in On-Premise Exchange? Either 2016 or 2019, that should not make much of a difference.
